- name: Apache Exercise Playbook
  hosts: all
  tasks:
    - name: Install httpd
      yum:
        name: httpd
        state: latest
    - name: Copying the index html file
      copy:
        content: "Hi Sanofi"
        dest: /var/www/html/index.html
    - name: Start service on system boot
      service:
        name: httpd
        state: started
    - name: Enable Firewall
      firewalld:
        service: http
        state: enabled
        permanent: yes
        immediate: yes
