- name: install the software
  yum:
    name: vsftpd
    state: present
- name: print something
  debug:
    msg: "{{ansible_fqdn}}"
- name: copy a file
  copy:
    content: "Hi All Welcome to {{ansible_hostname}}"
    dest: /tmp/motd
